Fixed GUI Guess
mucsci-students/2023sp-420-MediaTek pull request #202
Opened 2023-03-18 07:02 UTC by gabe2762

Added the longer than 15 letter constraint, and added the case where the user is told a correct guessed word was already guessed.

2023-03-18 08:30 UTC, auanmu requested changes
Since I’m on mobile hard for me to pick the exact line since it squishes the text. But the windows version you removed some extra stuff that I think needs to be there still. Compare what’s after the else statement in max and windows, it shows you getting rid of clear the input box and updating the rank in the windows version but the Mac file still has it. Should be the same, need keep those lines of code.

2023-03-18 13:40 UTC, tmhughes1 commented on MVC/view/austinguitest.py
> +        if len(input) < 4 or len(input) > 15:
I think this covers all cases, but I'll have to verify after testing it

2023-03-18 13:41 UTC, tmhughes1 commented on MVC/view/austinguitest.py
> -        #update the points and rank after every guess.
Why did you remove this part? The makeGuess function needs to still update points, rank, and clear the input box.

2023-03-18 13:42 UTC, tmhughes1 requested changes
Some code got removed from austinguitest in makeGuess that shouldn't have been! Please fix.

2023-03-18 20:35 UTC, tmhughes1 approved these changes
Thanks for fixing!

2023-03-19 00:46 UTC, auanmu approved these changes
Thanks for fixing it, great work Gabe!

2023-03-19 00:46 UTC, merged